"""Identity and access: tenants, users, memberships, roles, sessions, API keys.

Revision ID: 0002_identity_access
Revises: 0001_initial_infra
Create Date: 2026-08-12 01:00:00.000000+00:00

Every constraint is named explicitly. Alembic builds its own `MetaData` for
`op.create_table`, so the naming convention declared on `app.core.database.Base`
does not apply here - unnamed constraints would get PostgreSQL's defaults
(`tenants_pkey`, `tenants_slug_key`) and permanently disagree with the models.
The names below reproduce the convention by hand, which is what keeps a future
`alembic revision --autogenerate` from proposing a diff that does not exist.

The permission catalogue, the six system roles and their grants are seeded
here. That is reference data the authorization code cannot work without, not
business data: an empty `permissions` table means every authorization check
fails closed. It is duplicated from `app.modules.identity.domain` rather than
imported, because a migration must keep producing the same schema years after
the application code has moved on. `tests/unit/test_identity_migration.py`
asserts the two never drift apart.
"""

from collections.abc import Sequence
from typing import Final

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_identity_access"
down_revision: str | None = "0001_initial_infra"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# (slug, description) - mirrors domain.Permission / PERMISSION_DESCRIPTIONS.
PERMISSIONS: Final[tuple[tuple[str, str], ...]] = (
    ("tenant.read", "View tenant profile and settings."),
    ("tenant.update", "Change tenant profile and settings."),
    ("members.invite", "Invite people to the tenant."),
    ("members.manage", "Change or remove memberships and role assignments."),
    ("channels.connect", "Connect a messaging channel."),
    ("channels.manage", "Reconfigure or disconnect messaging channels."),
    ("conversations.read", "Read customer conversations."),
    ("conversations.reply", "Reply to customer conversations."),
    ("conversations.assign", "Assign conversations to teammates."),
    ("ai.configure", "Configure AI behaviour."),
    ("knowledge.manage", "Manage the knowledge base."),
    ("catalog.manage", "Manage the product catalog."),
    ("billing.manage", "Manage subscription, payment method and invoices."),
    ("apikeys.manage", "Create, rotate and revoke API keys."),
    ("audit.read", "Read the tenant audit log."),
)

# (slug, display name, description) - mirrors domain.RoleSlug / ROLE_DESCRIPTIONS.
ROLES: Final[tuple[tuple[str, str, str], ...]] = (
    ("owner", "Owner", "Full control of the tenant, including billing and ownership."),
    ("admin", "Admin", "Full control of the tenant except billing."),
    ("manager", "Manager", "Runs conversations, catalog, knowledge and AI configuration."),
    ("agent", "Agent", "Handles customer conversations."),
    ("billing_admin", "Billing Admin", "Manages subscription and billing only."),
    ("viewer", "Viewer", "Read-only access."),
)

_ALL: Final[tuple[str, ...]] = tuple(slug for slug, _ in PERMISSIONS)
_CONVERSATION_WORK: Final[tuple[str, ...]] = (
    "conversations.read",
    "conversations.reply",
    "conversations.assign",
)

# Owner is the only role with billing.manage. That single difference is what
# makes Admin safe to hand out - mirrors domain.DEFAULT_ROLE_GRANTS.
ROLE_GRANTS: Final[dict[str, tuple[str, ...]]] = {
    "owner": _ALL,
    "admin": tuple(slug for slug in _ALL if slug != "billing.manage"),
    "manager": (
        *_CONVERSATION_WORK,
        "tenant.read",
        "catalog.manage",
        "knowledge.manage",
        "ai.configure",
    ),
    "agent": (*_CONVERSATION_WORK, "tenant.read"),
    "billing_admin": ("tenant.read", "billing.manage"),
    "viewer": ("tenant.read", "conversations.read"),
}

_TABLES_IN_DROP_ORDER: Final[tuple[str, ...]] = (
    "audit_logs",
    "email_tokens",
    "api_keys",
    "sessions",
    "membership_roles",
    "role_permissions",
    "permissions",
    "roles",
    "memberships",
    "users",
    "tenants",
)


def _uuid_pk() -> sa.Column[sa.Uuid[object]]:
    """The identifier column shared by every identity table.

    No server default: identifiers are UUIDv7 values generated by the
    application (`app.platform.ids`), so that a row's primary key sorts by
    creation time and index writes stay local instead of scattering across the
    B-tree the way random v4 keys do.
    """
    return sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False)


def _created_at() -> sa.Column[sa.DateTime]:
    return sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )


def _updated_at() -> sa.Column[sa.DateTime]:
    return sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )


def _create_tenants() -> None:
    op.create_table(
        "tenants",
        _uuid_pk(),
        _created_at(),
        _updated_at(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="tenants_pk"),
        sa.UniqueConstraint("slug", name="tenants_slug_uq"),
        sa.CheckConstraint("status IN ('active', 'suspended')", name="tenants_status_ck"),
        sa.CheckConstraint("slug = lower(slug)", name="tenants_slug_normalised_ck"),
    )
    op.create_index("tenants_status_idx", "tenants", ["status"])


def _create_users() -> None:
    op.create_table(
        "users",
        _uuid_pk(),
        _created_at(),
        _updated_at(),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        # Argon2id digest. The plaintext is never stored, never logged and
        # never leaves the request that carried it.
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        sa.Column("session_epoch", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("failed_logins", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="users_pk"),
        sa.UniqueConstraint("email", name="users_email_uq"),
        # Uniqueness on a case-sensitive column only works if every stored
        # address is already lowercased, so the database enforces that rather
        # than trusting the application to have normalised first.
        sa.CheckConstraint("email = lower(email)", name="users_email_normalised_ck"),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deactivated')",
            name="users_status_ck",
        ),
        sa.CheckConstraint("session_epoch >= 0", name="users_session_epoch_ck"),
        sa.CheckConstraint("failed_logins >= 0", name="users_failed_logins_ck"),
    )


def _create_memberships() -> None:
    op.create_table(
        "memberships",
        _uuid_pk(),
        _created_at(),
        _updated_at(),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'invited'")),
        sa.Column("invited_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="memberships_pk"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_memberships_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_memberships_user_id_users",
            ondelete="CASCADE",
        ),
        # SET NULL: removing the person who sent an invitation must not remove
        # the membership that invitation created.
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["users.id"],
            name="fk_memberships_invited_by_id_users",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint("tenant_id", "user_id", name="memberships_tenant_id_user_id_uq"),
        sa.CheckConstraint(
            "status IN ('invited', 'active', 'suspended')",
            name="memberships_status_ck",
        ),
    )
    op.create_index("memberships_user_id_idx", "memberships", ["user_id"])
    op.create_index(
        "memberships_tenant_id_status_idx",
        "memberships",
        ["tenant_id", "status"],
    )


def _create_roles() -> None:
    op.create_table(
        "roles",
        _uuid_pk(),
        _created_at(),
        _updated_at(),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column("is_system", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.PrimaryKeyConstraint("id", name="roles_pk"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_roles_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "(tenant_id IS NULL) = is_system",
            name="roles_system_roles_have_no_tenant_ck",
        ),
    )
    # Two partial unique indexes rather than one UNIQUE (tenant_id, slug):
    # PostgreSQL treats NULLs as distinct, so the plain constraint would
    # happily accept two system roles both called 'owner'.
    op.create_index(
        "roles_slug_idx",
        "roles",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NULL"),
    )
    op.create_index(
        "roles_tenant_id_slug_idx",
        "roles",
        ["tenant_id", "slug"],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NOT NULL"),
    )


def _create_permissions() -> None:
    op.create_table(
        "permissions",
        _uuid_pk(),
        _created_at(),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.PrimaryKeyConstraint("id", name="permissions_pk"),
        sa.UniqueConstraint("slug", name="permissions_slug_uq"),
    )


def _create_role_permissions() -> None:
    op.create_table(
        "role_permissions",
        sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("permission_id", postgresql.UUID(as_uuid=True), nullable=False),
        _created_at(),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name="role_permissions_pk"),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name="fk_role_permissions_role_id_roles",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name="fk_role_permissions_permission_id_permissions",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "role_permissions_permission_id_idx",
        "role_permissions",
        ["permission_id"],
    )


def _create_membership_roles() -> None:
    op.create_table(
        "membership_roles",
        sa.Column("membership_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False),
        _created_at(),
        sa.PrimaryKeyConstraint("membership_id", "role_id", name="membership_roles_pk"),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name="fk_membership_roles_membership_id_memberships",
            ondelete="CASCADE",
        ),
        # RESTRICT: a role that is still assigned to somebody cannot be deleted
        # out from under them, which would silently strip permissions.
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name="fk_membership_roles_role_id_roles",
            ondelete="RESTRICT",
        ),
    )
    op.create_index("membership_roles_role_id_idx", "membership_roles", ["role_id"])


def _create_sessions() -> None:
    op.create_table(
        "sessions",
        _uuid_pk(),
        _created_at(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=True),
        # SHA-256 digests, never the tokens themselves: a database dump must
        # not be a list of usable session cookies.
        sa.Column("token_digest", sa.Text(), nullable=False),
        sa.Column("csrf_digest", sa.Text(), nullable=False),
        sa.Column("user_epoch", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="sessions_pk"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_sessions_user_id_users",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_sessions_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_digest", name="sessions_token_digest_uq"),
    )
    op.create_index("sessions_user_id_idx", "sessions", ["user_id"])
    op.create_index("sessions_tenant_id_user_id_idx", "sessions", ["tenant_id", "user_id"])
    # Supports the expiry sweep without scanning the table.
    op.create_index("sessions_absolute_expires_at_idx", "sessions", ["absolute_expires_at"])


def _create_api_keys() -> None:
    op.create_table(
        "api_keys",
        _uuid_pk(),
        _created_at(),
        _updated_at(),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        # key_id is the public half; secret_digest is SHA-256 of the secret
        # half. Looking a key up by key_id is one indexed read instead of a
        # scan that would have to hash every stored row.
        sa.Column("key_id", sa.Text(), nullable=False),
        sa.Column("secret_digest", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="api_keys_pk"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_api_keys_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name="fk_api_keys_created_by_id_users",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint("key_id", name="api_keys_key_id_uq"),
    )
    op.create_index(
        "api_keys_tenant_id_created_at_idx",
        "api_keys",
        ["tenant_id", "created_at"],
    )


def _create_email_tokens() -> None:
    op.create_table(
        "email_tokens",
        _uuid_pk(),
        _created_at(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("token_digest", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="email_tokens_pk"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_email_tokens_user_id_users",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_digest", name="email_tokens_token_digest_uq"),
        sa.CheckConstraint(
            "purpose IN ('email_verification', 'password_reset')",
            name="email_tokens_purpose_ck",
        ),
    )
    op.create_index(
        "email_tokens_user_id_purpose_idx",
        "email_tokens",
        ["user_id", "purpose"],
    )


def _create_audit_logs() -> None:
    op.create_table(
        "audit_logs",
        _uuid_pk(),
        _created_at(),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_api_key_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.PrimaryKeyConstraint("id", name="audit_logs_pk"),
        # Actor references are SET NULL so the trail outlives the person or key
        # it describes. An audit row that vanishes with its subject is not an
        # audit trail.
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_audit_logs_tenant_id_tenants",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name="fk_audit_logs_actor_user_id_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_api_key_id"],
            ["api_keys.id"],
            name="fk_audit_logs_actor_api_key_id_api_keys",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint("outcome IN ('success', 'failure')", name="audit_logs_outcome_ck"),
    )
    op.create_index(
        "audit_logs_tenant_id_created_at_idx",
        "audit_logs",
        ["tenant_id", "created_at"],
    )
    op.create_index(
        "audit_logs_actor_user_id_created_at_idx",
        "audit_logs",
        ["actor_user_id", "created_at"],
    )
    op.create_index(
        "audit_logs_action_created_at_idx",
        "audit_logs",
        ["action", "created_at"],
    )


def _seed_reference_data() -> None:
    """Insert the permission catalogue, the system roles and their grants.

    `gen_random_uuid()` comes from pgcrypto, enabled by revision
    0001_initial_infra. These rows are reference data with no natural ordering
    requirement, so a v4 identifier is fine here even though application rows
    use UUIDv7.
    """
    for slug, description in PERMISSIONS:
        op.execute(
            sa.text(
                "INSERT INTO permissions (id, created_at, slug, description) "
                "VALUES (gen_random_uuid(), now(), :slug, :description)"
            ).bindparams(slug=slug, description=description)
        )

    for slug, name, description in ROLES:
        op.execute(
            sa.text(
                "INSERT INTO roles "
                "(id, created_at, updated_at, tenant_id, slug, name, description, is_system) "
                "VALUES (gen_random_uuid(), now(), now(), NULL, :slug, :name, :description, true)"
            ).bindparams(slug=slug, name=name, description=description)
        )

    for role_slug, permission_slugs in ROLE_GRANTS.items():
        for permission_slug in permission_slugs:
            op.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_id, created_at) "
                    "SELECT r.id, p.id, now() FROM roles r, permissions p "
                    "WHERE r.tenant_id IS NULL AND r.slug = :role AND p.slug = :permission"
                ).bindparams(role=role_slug, permission=permission_slug)
            )


def upgrade() -> None:
    """Create the identity schema and seed its reference data."""
    _create_tenants()
    _create_users()
    _create_memberships()
    _create_roles()
    _create_permissions()
    _create_role_permissions()
    _create_membership_roles()
    _create_sessions()
    _create_api_keys()
    _create_email_tokens()
    _create_audit_logs()
    _seed_reference_data()


def downgrade() -> None:
    """Drop the identity schema.

    Dropped in reverse dependency order. Indexes go with their tables, and the
    seeded reference data goes with `permissions` and `roles`.
    """
    for table in _TABLES_IN_DROP_ORDER:
        op.drop_table(table)
